# Generated by Django 4.1.3 on 2024-05-21 19:23

from django.db import migrations, models
import fileApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('no_downloads', models.IntegerField(default=0)),
                ('no_emails_sent_to', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=fileApp.models.image_save_loc)),
            ],
        ),
    ]
